name: Conditional Product Deployment

on:
  workflow_dispatch:
    inputs:
      deploy_asrs:
        description: 'ASRS'
        required: true
        type: boolean
        default: false
      asrs_version:
        description: 'ASRS Version'
        required: true
        type: string
        default: 'v1.0.0'        
      deploy_sorter:
        description: 'Sorter'
        required: true
        type: boolean
        default: false
      sorter_version:
        description: 'Sorter Version'
        required: true
        type: string
        default: 'v1.0.0'  

jobs:
  asrs-deployment:
    if: ${{ github.event.inputs.deploy_asrs == 'true' }}
    runs-on: ubuntu-latest
    steps:
      - name: Build and Deploy ASRS
        run: echo "Deploying ASRS at version ${{ github.event.inputs.version }}"

  sorter-deployment:
    if: ${{ github.event.inputs.deploy_sorter == 'true' }}
    runs-on: ubuntu-latest
    steps:
      - name: Build and Deploy Sorter
        run: echo "Deploying sorter at version ${{ github.event.inputs.version }}"
